-- ==========================================================
-- SCRIPT DE BASE DE DATOS SUPABASE (POSTGRESQL)
-- Proyecto: Soluciones Cloud v1
-- Tabla: products (Compatible con entidad JPA Product)
-- ==========================================================

-- 1. Crear tabla 'products' con identificador autoincremental
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. Habilitar Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Política: Permitir lectura pública (coincide con GET /api/products público)
DROP POLICY IF EXISTS "Permitir lectura publica de productos" ON public.products;
CREATE POLICY "Permitir lectura publica de productos" 
ON public.products 
FOR SELECT 
USING (true);

-- Política: Permitir inserción, actualización y borrado al backend (conexión JDBC con rol postgres)
DROP POLICY IF EXISTS "Permitir acceso total al backend" ON public.products;
CREATE POLICY "Permitir acceso total al backend" 
ON public.products 
FOR ALL 
USING (true)
WITH CHECK (true);

-- 3. Índice para búsquedas eficientes por categoría
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);

-- 4. Datos iniciales (Seed Data coincidente con DataInitializer.java)
INSERT INTO public.products (name, description, price, category) 
VALUES
    ('Laptop Dell XPS 15', 'Intel Core i7, 16GB RAM, 512GB SSD', 1499.99, 'Hardware'),
    ('Monitor LG UltraWide 34"', 'Resolución WQHD 144Hz IPS', 599.50, 'Periféricos'),
    ('Suscripción Azure Cloud', 'Créditos de cómputo y servicios cognitivos', 250.00, 'Servicios Cloud')
ON CONFLICT DO NOTHING;

-- ==========================================================
-- Microservicio / Tabla: orders (Compatible con entidad JPA Order)
-- ==========================================================

-- 5. Crear tabla 'orders' con identificador autoincremental
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    product_id BIGINT,
    product_name VARCHAR(255),
    quantity INTEGER DEFAULT 1,
    unit_price DOUBLE PRECISION,
    total_amount DOUBLE PRECISION,
    status VARCHAR(50) DEFAULT 'CONFIRMED',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 6. Habilitar Row Level Security (RLS) para 'orders'
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Política: Permitir acceso total al backend (conexión JDBC)
DROP POLICY IF EXISTS "Permitir acceso total al backend para orders" ON public.orders;
CREATE POLICY "Permitir acceso total al backend para orders" 
ON public.orders 
FOR ALL 
USING (true)
WITH CHECK (true);

-- 7. Índices para consultas por usuario y fecha
CREATE INDEX IF NOT EXISTS idx_orders_user_email ON public.orders(user_email);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);

