spring.application.name=demo

# Server port
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# AWS Cognito Configuration
cognito.region=us-east-1
cognito.user-pool-id=us-east-1_OL9DjB9XL
cognito.client-id=53acsgrc0tneq7jhigesj93g8r
cognito.jwks-url=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_OL9DjB9XL/.well-known/jwks.json
cognito.issuer=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_OL9DjB9XL
